### ISSUE TITLE
[BUG] Special 'clear_notification' pseudo-notification is shown as a regular notification

### ISSUE THREAD

**Issue by jpbaril** [muniter/halinuxcompanion#40]
**Describe the bug**

**To Reproduce**
1. Send a persistent notification to the device with some message.
2. Send a second notification to the device with special 'clear_notification' message.

**Expected behavior**
That second special "pseudo-notification" should make the persistent first one to disappear.

**Additional context**
What happens is that the special pseudo-notification 'clear_notification' is shown as a regular notification with 'clear_notification' as the notification's body content.

**Comment by muniter** [comment]
This is implemented and it works on my install. 

Here's the implementation:

https://github.com/muniter/halinuxcompanion/blob/master/halinuxcompanion%2Fnotifier.py#L285-L288

Can you share the payloads you are using from homeassistant to send the notifications.

**Comment by jpbaril** [comment]
Notify group:
```
notify:
  - platform: group
    name: "All my devices"
    unique_id: all_my_devices
    services:
      - action: mobile_app_pixel_8a
      - action: mobile_app_tab_s3
      - action: mobile_app_blackbox_ng
```

Original permanent notification:
```
action: notify.all_my_devices
metadata: {}
data:
  message: Someone rang
  title: Doorbell 🔔
  data:
    ttl: 0
    priority: high
    channel: intercom
    importance: high
    persistent: true
    tag: intercom
    image: /api/camera_proxy/camera.reolink_rlc_81ma_zoom_snapshots_clear
    actions:
      - action: intercom_ignore
        title: Ignore ✖
      - action: intercom_open
        title: Unlock door 🔓
enabled: true
```

Clearing notification:
```
action: notify.all_my_devices
data:
  message: clear_notification
  data:
    tag: intercom
```
